Comentarios de la clase, más ejemplos
rlyehlab/taller-web pull request #5
Opened 2018-01-04 23:37 UTC by deimidis

Cambios agregados durante la clase con aclaraciones y objetos

2018-01-05 15:22 UTC, exos requested changes
Unos pocos cambios

2018-01-05 15:22 UTC, exos commented on clases/03.md
> + }
Agregar default

2018-01-05 15:22 UTC, exos commented on clases/03.md
> +  console.log("hola"+this.nombre);
s/"hola"/"hola "/

2018-01-05 15:22 UTC, exos commented on clases/03.md
> +}
Cambiemos el id de "contenedor", no solo para que sea mas descriptivo, sino también porque puden tratar de correr ambos ejemplos en un mismo documento (como pasó el jueves con un@ estudiante)

2018-01-07 22:30 UTC, Gahen approved these changes
Joya

2018-01-07 22:31 UTC, merged